# Generated by Django 4.2.4 on 2023-08-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Playing Category',
            },
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tournament Type',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tournament_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('numbers_of_rounds', models.IntegerField(blank=True, null=True)),
                ('surface', models.CharField(max_length=100)),
                ('tournament_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamenttype')),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.playingcategory')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournaments')),
            ],
            options={
                'verbose_name_plural': 'Tournament Playing Category',
            },
        ),
    ]
