# Generated by Django 4.2.4 on 2023-08-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='name',
        ),
    ]
